# 시스템 XKB 설정을 덮어쓰도록 허용
Allow Overriding System XKB Settings=True
# 항상 자판을 그룹 자판으로만 지정
AlwaysSetToGroupLayout=True
# Set client disconnect mode to terminate (Need Restart)
ClientDisconnectModeTerminate=Yes

