allow_remote_control yes

include ./ayu_light.conf
font_family      jetbrains mono nerd font
font_size        15
bold_font        auto
italic_font      auto
bold_italic_font auto
mouse_hide_wait  2.0
cursor_shape     block
url_color        #89B4FA
url_style dashed
#Close the terminal without confirmation
confirm_os_window_close 1
background_opacity 0.95
shell=zsh

symbol_map U+AC00-U+D7AF MaruBuri
symbol_map U+1100-U+11FF MaruBuri
symbol_map U+3130-U+318F MaruBuri

map ctrl+backspace send_text all \x17
map ctrl+delete send_text all \x1b[3;5~
map f1 launch --stdin-source=@screen_scrollback --stdin-add-formatting less +G -R

# Open search with ctrl+shift+f
map ctrl+shift+f show_scrollback
map super+shift+f launch ~/.config/kitty/scripts/file_search.sh

map ctrl+f4 close_tab
map ctrl+shift+t new_tab_with_cwd

mouse_map left click ungrabbed mouse_handle_click prompt
mouse_map ctrl+left click ungrabbed mouse_handle_click link